### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by xicobiu** [JemPH/qdr_remastered#1]
Input: 2
Signed in successfully - Studio account.

Input URL: **https://open.qobuz.com/album/0093624932130**
Traceback (most recent call last):
  File "C:\Users\\Music\qdr_remastered\qdr.py\__main__.py", line 599, in <module>
    main(False, False, cfg, tag_cfg, None, cli)
  File "C:\Users\\Music\qdr_remastered\qdr.py\__main__.py", line 413, in main
    album_fol = al_meta['ALBUMARTIST'] + " - " + al_meta['ALBUM'] + f" ({al_meta['YEAR']}) [{src_meta['maximum_bit_depth']}B-{src_meta['maximum_sampling_rate']}kHz] [{src_meta['id']}] [{src_meta['album']['version']}]"
KeyError: 'album'

An exception has occurred. Press enter to exit.

**Comment by JemPH** [comment]
problem, fix try again.

**Comment by RequestKing** [comment]
Hello. I'm not expert (I'm a beginner to be honest). I need a video tutorial to be able to use "qdr_remastered" in qobuz.com
Thanks in advance.
